### ISSUE TITLE
How do we use this ? help us setup ! Accounts [username:password]

### ISSUE THREAD

**Issue by SENPAY98K** [KibbeWater/SteamAccountChecker#2]
Hi
i have accounts to check formatted as [username:password]
i tried using this project but i have no clue on how to use it.

Can you help guiding us set it up?

**Comment by SENPAY98K** [comment]
i only get this thing empty after checking the importing 
![image](https://user-images.githubusercontent.com/77079047/129494744-09a758af-01d4-4029-9c04-b612ae4b6b29.png)

**Comment by KibbeWater** [comment]
This is a very old repo and to be honest the dependencies I've used are probably outdated by now. Make sure to check settings as you might need to input something, it was so long ago!
